apiVersion: apps/v1
kind: Deployment
metadata:
  name: denouement
  namespace: denouement
  labels:
    app.kubernetes.io/name: denouement
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: denouement
  template:
    metadata:
      labels:
        app.kubernetes.io/name: denouement
    spec:
      imagePullSecrets: 
      - name: azure-container-registry-credentials
      containers:
        - name: denouement
          image: denouementregistry.azurecr.io/manshaehsan/denouementapi:latest
          ports:
            - containerPort: 8080
