name: simple-node-app
kind: pipeline
type: kubernetes
trigger:
  branch:
    - master
    - gc
steps:
  - name: build-push
    image: ubuntu
    environment:
      gcloud_sa:
        from_secret: gcloud_sa
      gcloud_sa_json:
        from_secret: gcloud_sa_json
    commands:
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl
      - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y
      - gcloud auth activate-service-account ${gcloud_sa} --key-file=${gcloud_sa_json}
      - gcloud auth list
  - name: deploy
    environment:
      config:
        from_secret: k8s_config
    image: ubuntu
    commands:
      - mkdir ~/./kube
      - echo $config ~/.kube/config
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl
      - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" |  tee /etc/apt/sources.list.d/kubernetes.list
      - apt-get update
      - apt-get install -y kubectl
      - kubectl version --client
      - kubectl apply -f service.yml
      - kubectl apply -f cr-cred.yml
      - kubectl apply -f dep.yml
  - name: slack-notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_notification_webhook
    channel: automation
