kind: pipeline 
type: kubernetes
name: simple-node-app
trigger:
 branch:
 - master
steps: 
- name: image-build-push
  image: plugins/docker
  settings:
   username:
    from_secret: docker_username
   password:
    from_secret: docker_password
   repo: index.docker.io/v1/manshaehsan/buildpacks
   registry: index.docker.io/v1/
   tags: latest
    
