kind: pipeline 
type: kubernetes
name: simple-node-app
trigger:
 branch:
 - master
steps: 
- name: image-build-push
  image: plugins/docker
  settings:
   username: 
    from_secret: azure_username
   password: 
    from_secret: azure_password
   repo: denouementregistry.azurecr.io/manshaehsan/denouementapi
   registry: denouementregistry.azurecr.io
   tags: latest
    
