name: simple-node-app
kind: pipeline
type: kubernetes
trigger:
  branch:
    - master
    - gcr
steps:

  - name: publish  
    image: plugins/gcr
    settings:
     repo: gcr.io/my-project-st-308107/copyright
     tags: ${COMMIT_SHA}
     json_key:
       from_secret: google_credentials
  - name: deploy
    environment:
      config:
       from_secret: k8s_config
    image: ubuntu
    commands:
      - mkdir ~/./kube
      - echo $config ~/.kube/config
      - apt-get update 
      - apt-get install -y apt-transport-https ca-certificates curl
      - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" |  tee /etc/apt/sources.list.d/kubernetes.list
      - apt-get update
      - apt-get install -y kubectl
      - kubectl version --client
      - kubectl apply -f service.yml
      - kubectl apply -f cr-cred.yml
      - kubectl apply -f dep.yml
  - name: slack-notification
    image: plugins/slack
    settings: 
     webhook:
      from_secret: slack_notification_webhook
    channel: automation
