kind: pipeline 
type: kubernetes
name: simple-node-app
trigger:
 branch:
 - master
steps: 
- name: image-build-push
  image: plugins/docker
  settings:
   username:
    from_secret: docker_username
   password:
    from_secret: docker_password
   repo: https://index.docker.io/v1/manshaehsan/blackhole
   registry: https://index.docker.io/v1
   tags: latest
    
