apiVersion: v1
kind: Service
metadata:
  name: denouement
  namespace: drone
spec:
  type: LoadBalancer
  selector:
     app.kubernetes.io/name: denouement
  ports:
    - port: 8080
      targetPort: 8080
